using Lib;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace _2
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    /// 
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// 
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    class Program
    {
        static void Main(string[] args)
        {
            var answer = FibonacciGenerator.Generate()
                .TakeWhile((value) => value <= 4000000)
                .Where(v => v % 2 == 0)
                .Select(v => (int)v)
                .Sum();

            Console.WriteLine(answer);
            Console.ReadKey();
        }
    }
}
