using Lib;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Text;
using System.Threading.Tasks;

namespace _044
{
    /// <summary>
    /// Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
    /// 
    /// 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
    /// 
    /// It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
    /// 
    /// Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
    /// </summary>
    class Program
    {
        static void Main(string[] args)
        {
            var pentagonNums = PentagonalNumberGenerator.Generate().TakeWhile(n => n < 10000000).ToList();

            var answer = (from p1 in pentagonNums
                          from p2 in pentagonNums
                          where p1 > p2
                          where pentagonNums.Contains(p1 + p2)
                          where pentagonNums.Contains(p1 - p2)
                          select p1 - p2)
                         .Min();
            Console.WriteLine(answer);

            Console.WriteLine("Done");
            Console.ReadKey();
        }
    }
}
